# meta
author_introduction: hoge
twitter_id: takachan_mirai
github_id: takachan-mirai
facebook_id: 827488554056254

# UI
postcard_intro_length: 140
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# other
google_analytics_id: UA-116350727-1
google_analytics_developer_key: takachan-mirai.github.io_developer
